force-app/main/default/objects/Template__c/Template__c.object-meta.xml
<CustomObject>
    <label>Template</label>
    <nameField>
        <displayFormat>TA-{0000}</displayFormat>
        <label>Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Template__c/fields/HTML_Structure__c.field-meta.xml
<CustomField>
    <fullName>HTML_Structure__c</fullName>
    <label>HTML Structure</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Template_mapping_output__c/Template_mapping_output__c.object-meta.xml
<CustomObject>
    <label>Template mapping output</label>
    <nameField>
        <displayFormat>TMN-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Template mapping outputs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Template_Mapping_Output__c/fields/Field_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Field_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Field Mapping</label>
    <referenceTo>Mapping_Config__c</referenceTo>
    <relationshipLabel>Template Mapping Outputs</relationshipLabel>
    <relationshipName>Template_Mapping_Outputs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Template_Mapping_Output__c/fields/Output_Html__c.field-meta.xml
<CustomField>
    <fullName>Output_Html__c</fullName>
    <label>Output Html</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Template_Mapping_Output__c/fields/Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Template_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Template Id</label>
    <referenceTo>Template__c</referenceTo>
    <relationshipLabel>Template Mapping Outputs</relationshipLabel>
    <relationshipName>Template_Mapping_Outputs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TemplateProcessor.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 04-22-2026
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class TemplateProcessor {

    @AuraEnabled
    public static Id generateHtmlFromTemplate(Id accountId, Id templateId, Id mappingId) {

        try {

            if (accountId == null || templateId == null || mappingId == null) {
                throw new AuraHandledException('Please select all fields');
            }
            String html = [
                SELECT HTML_Structure__c
                FROM Template__c
                WHERE Id = :templateId
                LIMIT 1
            ].HTML_Structure__c;

            if (String.isBlank(html)) {
                throw new AuraHandledException('Template HTML is empty');
            }

            Map<String, Set<String>> objectFieldsMap = new Map<String, Set<String>>();

            Matcher m = Pattern.compile('\\{!([a-zA-Z0-9_]+)\\.([a-zA-Z0-9_]+)\\}').matcher(html);

            while (m.find()) {
                String obj = m.group(1);
                String field = m.group(2);

                if (!objectFieldsMap.containsKey(obj)) {
                    objectFieldsMap.put(obj, new Set<String>());
                }

                objectFieldsMap.get(obj).add(field);
            }

            
            for (String objName : objectFieldsMap.keySet()) {

                if (objName == 'Account') {

                    html = mergeParentObjectData(
                        html,
                        objName,
                        accountId,
                        objectFieldsMap.get(objName)
                    );

                } else {

                    html = mergeChildObjectData(
                        html,
                        objName,
                        accountId,
                        objectFieldsMap.get(objName)
                    );
                }
            }

            Template_Mapping_Output__c rec = new Template_Mapping_Output__c();

            rec.Account__c = accountId;
            rec.Master_Record_Id__c = String.valueOf(accountId);
            rec.Template_Id__c = templateId;
            rec.Field_Mapping__c = mappingId;
            rec.Output_Html__c = html;

            insert rec;

            return rec.Id;

        } catch (Exception e) {
            throw new AuraHandledException('Error: ' + e.getMessage());
        }
    }

    
    private static String mergeParentObjectData(
        String html,
        String objectApiName,
        Id recordId,
        Set<String> fields
    ) {

        fields.add('Id');

        String query = 'SELECT ' + String.join(new List<String>(fields), ',') +
                       ' FROM ' + objectApiName +
                       ' WHERE Id = :recordId LIMIT 1';

        SObject sobj = Database.query(query);

        for (String fieldName : fields) {
            Object val = sobj.get(fieldName);

            html = html.replace(
                '{!' + objectApiName + '.' + fieldName + '}',
                val != null ? String.valueOf(val) : ''
            );
        }

        return html;
    }

    
    private static String mergeChildObjectData(
        String html,
        String objectApiName,
        Id accountId,
        Set<String> fields
    ) {

        fields.add('Id');

        String relationshipField = 'AccountId';

        String query = 'SELECT ' + String.join(new List<String>(fields), ',') +
                       ' FROM ' + objectApiName +
                       ' WHERE ' + relationshipField + ' = :accountId LIMIT 1';

        List<SObject> records = Database.query(query);

        if (!records.isEmpty()) {

            SObject sobj = records[0];

            for (String fieldName : fields) {
                Object val = sobj.get(fieldName);

                html = html.replace(
                    '{!' + objectApiName + '.' + fieldName + '}',
                    val != null ? String.valueOf(val) : ''
                );
            }

        } else {

            try {
                html = html.replaceAll(
                    '(?s)' + objectApiName + ' Details.*?<table>.*?</table>',
                    ''
                );
                
            } catch (Exception e) {}
        }

        return html;
    }
}